export const GET_CHATS_USER = 'CHAT/GET_CHATS_USER'
export const INIT_MESSAGE   = 'MESSAGE/INIT_MESSAGE'
export const SET_NEW_MESSAGE = 'MESSAGE/SET_NEW_MESSAGE'
export const SET_USERS_ONLINE   = 'CHAT/SET_USERS_ONLINE'