export const GET_USERS_IN_CHAT  = 'CHAT/GET_USERS_IN_CHAT'
export const GET_LAST_MSG       = 'CHAT/GET_LAST_MSG'
export const SET_LAST_MSG       = 'CHAT/SET_LAST_MSG'

export const SET_MESSAGE        = 'MESSAGE/SET_MESSAGE'
export const SET_MESSAGE_STORE  = 'MESSAGE/SET_MESSAGE_STORE'
export const INIT_MESSAGE       = 'MESSAGE/INIT_MESSAGE'